[package]
name = "BAMetrics"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bam="0.1"
clap="4.4"
rstest = "0.18"
serde = "1.0"
serde_json = "1.0"

[dev-dependencies]
rstest = "0.18"
