name: Rust

on:
  push:
    branches: [ "main", "development" ]
  pull_request:
    branches: [ "main", "development" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
          os: [ ubuntu-latest, windows-latest, macos-latest ]

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests and collect coverage
      run: |
          cargo test --verbose
          cargo install grcov
          grcov ./target/debug/ -s . -t coveralls --llvm --branch --ignore-not-existing -o ./coverage.json --token ${{ secrets.COVERALLS_REPO_TOKEN }}
    - name: Upload coverage to Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ./coverage.json
        flag-name: run-${{ matrix.rust }}
        parallel: true
